name 'lfs_modder'
maintainer 'Adam BALAZS'
maintainer_email 'balazs.adam@lfs.hu'
license 'all_rights'
description 'Installs/Configures lfs_modder'
long_description 'Installs/Configures lfs_modder'
issue_url 'https://github.com/balazsadam/chef-lfs_modder/issues'
source_url 'https://github.com/balazsadam/chef-lfs_modder'
version '1.0.9'
